<?php
// auto-generated by sfRoutingConfigHandler
// date: 2016/01/11 13:11:28
return array(
'job' => new sfPropelRoute('/job.:sf_format', array (
  'module' => 'job',
  'action' => 'index',
  'sf_format' => 'html',
), array (
  'sf_method' => 'GET',
), array (
  'model' => 'JobeetJob',
  'type' => 'list',
)),
'job_show_user' => new sfPropelRoute('/job/:company_slug/:location_slug/:id/:position_slug', array (
  'module' => 'job',
  'action' => 'show',
), array (
  'id' => '\\d+',
  'sf_method' => 
  array (
    0 => 'GET',
  ),
), array (
  'model' => 'JobeetJob',
  'type' => 'object',
  'method_for_criteria' => 'doSelectActive',
)),
'homepage' => new sfRoute('/', array (
  'module' => 'job',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
'category' => new sfPropelRoute('/category/:slug.:sf_format', array (
  'module' => 'category',
  'action' => 'show',
  'sf_format' => 'html',
), array (
  'sf_format' => '(?:html|atom)',
), array (
  'model' => 'JobeetCategory',
  'type' => 'object',
)),
'api_jobs' => new sfPropelRoute('/api/:token/jobs.:sf_format', array (
  'module' => 'api',
  'action' => 'list',
), array (
  'sf_format' => '(?:xml|json|yaml)',
), array (
  'model' => 'JobeetJob',
  'type' => 'list',
  'method' => 'getForToken',
)),
'affiliate' => new sfPropelRouteCollection(array (
  'model' => 'JobeetAffiliate',
  'actions' => 
  array (
    0 => 'new',
    1 => 'create',
  ),
  'object_actions' => 
  array (
    'wait' => 'get',
  ),
  'name' => 'affiliate',
  'requirements' => 
  array (
  ),
)),
'job_new' => new sfPropelRoute('/job/new.:sf_format', array (
  'module' => 'job',
  'action' => 'new',
  'sf_format' => 'html',
), array (
  'sf_method' => 'GET',
), array (
  'model' => 'JobeetJob',
  'type' => 'object',
)),
'job_create' => new sfPropelRoute('/job.:sf_format', array (
  'module' => 'job',
  'action' => 'create',
  'sf_format' => 'html',
), array (
  'sf_method' => 'POST',
), array (
  'model' => 'JobeetJob',
  'type' => 'object',
)),
'job_edit' => new sfPropelRoute('/job/:id/edit.:sf_format', array (
  'module' => 'job',
  'action' => 'edit',
  'sf_format' => 'html',
), array (
  'sf_method' => 'GET',
), array (
  'model' => 'JobeetJob',
  'type' => 'object',
)),
'job_update' => new sfPropelRoute('/job/:id.:sf_format', array (
  'module' => 'job',
  'action' => 'update',
  'sf_format' => 'html',
), array (
  'sf_method' => 'PUT',
), array (
  'model' => 'JobeetJob',
  'type' => 'object',
)),
'job_delete' => new sfPropelRoute('/job/:id.:sf_format', array (
  'module' => 'job',
  'action' => 'delete',
  'sf_format' => 'html',
), array (
  'sf_method' => 'DELETE',
), array (
  'model' => 'JobeetJob',
  'type' => 'object',
)),
'job_show' => new sfPropelRoute('/job/:id.:sf_format', array (
  'module' => 'job',
  'action' => 'show',
  'sf_format' => 'html',
), array (
  'sf_method' => 'GET',
), array (
  'model' => 'JobeetJob',
  'type' => 'object',
)),
'job_publish' => new sfPropelRoute('/job/:id.:sf_format', array (
  'module' => 'job',
  'action' => 'publish',
  'sf_format' => 'html',
), array (
  'sf_method' => 'PUT',
), array (
  'model' => 'JobeetJob',
  'type' => 'object',
)),
);
