<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/01/11 13:11:26
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
